### ISSUE TITLE
Issues with your demo

### ISSUE THREAD

**Issue by mbrunet4** [shu223/SocialAPIHelpers#1]
You have Deprecations and a Semantic Issue in SVProgressHUD.m

And an Arc Semantic issue in your ViewController for your demo:
-No known class method for selector 'newsfeedForAccount:withLocation:handler:

**Comment by shu223** [comment]
Thanks, fixed!

https://github.com/shu223/SocialAPIHelpers/commit/5cb4d266699ac8475d1535353847bb38389af943
